### ISSUE TITLE
React warnings when using FacebookShareButton component

### ISSUE THREAD

**Issue by edhollinghurst** [Bunlong/next-share#1]
When using the `FacebookShareButton` component I'm getting the following React warnings:

- React does not recognize the `windowWidth` prop on a DOM element.
- React does not recognize the `windowHeight` prop on a DOM element.
- React does not recognize the `networkLink` prop on a DOM element.
- React does not recognize the `disabledStyle` prop on a DOM element.
- React does not recognize the `openShareDialogOnClick` prop on a DOM element.
- React does not recognize the `resetButtonStyle` prop on a DOM element.

I'm also using the `TwitterShareButton` and `WhatsappShareButton` components and not seeing these warnings when using those components.

**Comment by helloitsm3** [comment]
> When using the `FacebookShareButton` component I'm getting the following React warnings:
> 
> * React does not recognize the `windowWidth` prop on a DOM element.
> * React does not recognize the `windowHeight` prop on a DOM element.
> * React does not recognize the `networkLink` prop on a DOM element.
> * React does not recognize the `disabledStyle` prop on a DOM element.
> * React does not recognize the `openShareDialogOnClick` prop on a DOM element.
> * React does not recognize the `resetButtonStyle` prop on a DOM element.
> 
> I'm also using the `TwitterShareButton` and `WhatsappShareButton` components and not seeing these warnings when using those components.

Having this issue too. Are you currently working on a pull request to fix this?

**Comment by willvlad** [comment]
Same here: React does not recognize the `windowWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `windowwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by helloitsm3** [comment]
> Same here: React does not recognize the `windowWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `windowwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

I'ved added a PR to fix this. Waiting for @Bunlong to accept the PR.

**Comment by willvlad** [comment]
Any update?

**Comment by willvlad** [comment]
If it's taking so long, would you mind forking it and posting a link here to your fix?

**Comment by helloitsm3** [comment]
> If it's taking so long, would you mind forking it and posting a link here to your fix?

https://github.com/helloitsm3/next-share

**Comment by Bunlong** [comment]
Dear all, I was fixed by @helloitsm3 . Thank you so much!
