### ISSUE TITLE
Multiple hashtags for facebook

### ISSUE THREAD

**Issue by malinkaphann** [Bunlong/next-share#29]
How to use your library if I want to have multiple hashtags for facebook?
The document says about using a single "hashtag" of type string; but does not mention anything about multiple hashtags at all for facebook.

**Comment by Bunlong** [comment]
@malinkaphann Facebook has updated their [policies](https://developers.facebook.com/docs/instagram-api/guides/hashtag-search/). so now we can provide a Hashtag and no more. Thanks!
