### ISSUE TITLE
Does FacebookMessengerShareButton work without an app ID?

### ISSUE THREAD

**Issue by mikexavier** [Bunlong/next-share#45]
I'm getting an error from Facebook when using the FacebookMessengerShareButton

```
Sorry, this content isn't available right now
The link you followed may have expired, or the page may only be visible to an audience you're not in.
```

Maybe something has changed with their API or perhaps there are settings I've missed?

Thx! :)

**Comment by frederikvanhevel** [comment]
Same issue here? Any update?

**Comment by Bunlong** [comment]
@mikexavier, @frederikvanhevel FacebookMessengerShareButton required `appId` props.

```tsx
import {
  FacebookMessengerShareButton,
  FacebookMessengerIcon,
} from 'next-share';

<FacebookMessengerShareButton
  url={'https://github.com/next-share'}
  appId={''}
>
  <FacebookMessengerIcon size={32} round />
</FacebookMessengerShareButton>
```

**Comment by mikexavier** [comment]
ok, thanks, I haven't set up an app and tried this yet, but it looks like the docs need updating if this is a required prop.

ref: https://github.com/Bunlong/next-share#-facebookmessengersharebutton-props

🙏🏼

**Comment by Bunlong** [comment]
@frederikvanhevel the docs is updated. Thanks 🙏🏼
