### ISSUE TITLE
"added 1060 packages" with 7 high vulnerabilities?

### ISSUE THREAD

**Issue by florianwalther-private** [Bunlong/next-share#65]
Great and useful library! But I have a problem.
When I install the latest version of this library, it adds **1060 packages** with **7 high vulnerabilities**. When I install v0.13.0, I only get 130 and no vulnerabilities. What's the cause of this?

**Comment by flux0uz** [comment]
Same thing for us! These vulnerabilities appear from the version (v0.14.0) that supports React 18. By running the `audit fix --force`, the library is downgraded to version 0.12.1

**Comment by haschdl** [comment]
That's quite a big deal! Hoping to get attention from maintainers to fix that.

**Comment by Bunlong** [comment]
@florianwalther-private, @flux0uz, @haschdl 

The issue was fixed in next-share version 0.18.2. Thanks!

**Comment by florianwalther-private** [comment]
@Bunlong Well done! Thank you very much!

**Comment by Bunlong** [comment]
@florianwalther-private My pleasure! Thanks!
