### ISSUE TITLE
LinkedinShareButton not populating title nor summary data

### ISSUE THREAD

**Issue by josem-gp** [Bunlong/next-share#68]
Hi,

First of all thank you for this amazing package!

I am trying to share some url to LinkedIn with a title and a summary:

```
<LinkedinShareButton 
    url={'https://github.com/next-share'}
    title={'next-share is a social share buttons for your next React apps.'}
    summary={'This is a test for summary'}
>
  <LinkedinIcon size={32} round />
</LinkedinShareButton>
```

But it doesn't seem to work. Only the `url` props is working somehow. Is there any way to work around this? Thanks!

**Comment by Navaneeth-Sharma** [comment]
Hi @josem-gp, Did you find any solution for this ?

**Comment by josem-gp** [comment]
Not really.. still waiting for any update on this

**Comment by Bunlong** [comment]
@josem-gp, @Navaneeth-Sharma 

Linkedin API was updated in next-share version 0.18.4.

Please check the [document](https://github.com/Bunlong/next-share/#-linkedinsharebutton-props). Thanks!
