### ISSUE TITLE
Warning: Support for defaultProps will be removed in a future major release

### ISSUE THREAD

**Issue by Nicolab** [Bunlong/next-share#71]
Hello,

Thanks for this useful package ;)

There is this big warning in the console:

```
Warning: n: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

 at n (webpack-internal:///(app-client)/./node_modules/.pnpm/next-share@0.19.0_react@18.2.0/node_modules/next-share/dist/next-share.es.js:70:2471)
```

**Comment by ShaneYu** [comment]
I can confirm this is still occurring in version 0.20.0 also.

**Comment by ndpniraj** [comment]
The error is comming from Icon component using inside the buttons, I changed the Icon with custom SVG icons and there is no warning.

**Comment by maykon-oliveira** [comment]
Any news?

**Comment by joemcbroom** [comment]
https://github.com/Bunlong/next-share/pull/80

**Comment by pife00** [comment]
As said ndpniraj the problem are icons, this works for me in next 13.4, i used react icon

 <TwitterShareButton url={shareUrl} title={`${post.title}`} >
            <AiOutlineTwitter size={32}/>
  </TwitterShareButton>
